"""second mig

Revision ID: 1528add0a38a
Revises: d6e9c7356463
Create Date: 2023-08-05 16:12:03.747900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1528add0a38a'
down_revision = 'd6e9c7356463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.String(length=4),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
